version: '3.8'
services:
  mysql:
    image: mysql:8.0.37  # Sử dụng phiên bản MySQL 8.0.37
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   # Mật khẩu root
      MYSQL_DATABASE: mydb        # Tạo sẵn database tên 'mydb'
      MYSQL_USER: user            # Tạo user mới
      MYSQL_PASSWORD: password    # Mật khẩu cho user mới
    ports:
      - "3309:3306"  # Mở cổng 3306 để kết nối từ bên ngoài
    volumes:
      - mysql_data:/var/lib/mysql  # Lưu trữ dữ liệu để không bị mất khi container tắt

volumes:
  mysql_data:
