version: "3.8"

services:
  # ======================
  # MySQL Database
  # ======================
  mysql:
    image: mysql:8.0.37
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # ======================
  # Spring Boot App
  # ======================
  app:
    image: eclipse-temurin:17-jdk
    container_name: spring_app
    depends_on:
      - mysql
    volumes:
      - ./:/app
    working_dir: /app
    command: java -jar DTN2507HelloVTI-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"

volumes:
  mysql_data:

